version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins:/var/jenkins_home
      - ./tomcat/webapps:/var/jenkins_home/workspace
    networks:
      - my_network

  tomcat:
    image: tomcat:latest
    ports:
      - "8081:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    networks:
      - my_network

networks:
  my_network:
    driver: bridge